# Generated by Django 5.1.5 on 2025-02-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, choices=[('Movistar', 'Movistar'), ('Claro', 'Claro'), ('Personal', 'Personal'), ('Tuenti', 'Tuenti')], max_length=50, null=True),
        ),
    ]
